services:
  video-processor:
    build: .
    volumes:
      - .:/app
    ports:
      - "3330:3330"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "node"]
    tty: true
    stdin_open: true
