services:
  video-processor:
    environment:
      - NODE_ENV=development # production or development
      - HTTP_BEARER_TOKEN=mysecrettoken
    ports:
      - "3330:3330"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npm run node"]
    tty: true
    stdin_open: true
